### ISSUE TITLE
handle object; text field cropping before positioning & styles are captured + collapse symbols then ungroup their assets (see comments) 

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/designengine.ai#534]

**Comment by jasonfesta** [comment]
not sure we can process symbols for inspect, maybe for parts. But inspect causes everything to be flat because it doesn't break into the symbol for it's contents.

we need to detach each symbol then process the group

**Comment by mtholcombe** [comment]
- [X] Textfield processing
- [X] Added db tables for symbols
- [X] Detached 1st level in nested master symbols, then writing masters to db
- [ ] Write symbols w/in artboards to db w/ master assoc
- [ ] Treat symbols like groups, display parts list
