### ISSUE TITLE
presenter mode

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/designengine.ai#537]
![render](https://user-images.githubusercontent.com/1239243/52918089-ebe39a80-32a7-11e9-8441-be5424fe3887.png)

**Comment by jasonfesta** [comment]
[presenter.pdf](https://github.com/de-ai/designengine.ai/files/2885426/presenter.pdf)

**Comment by mtholcombe** [comment]
- [X] Helper functions to sort/filter/flatten/etc artboards & slices arrays for easier access
- [X] Broke out tabs into components for re-use
- [X] New tabs work for code + list
- [X] Load state cleanup (ongoing)
- [ ] Better zoom detection
- [ ] Artboard switching / deeplink
- [ ] PDF gen + other zip file stuff
