### ISSUE TITLE
Free Parts need to show parts not entire views, maybe we display symbols and when you rollover each you see the parts that make up that symbol or group

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/designengine.ai#554]

**Comment by jasonfesta** [comment]
[parts.pdf](https://github.com/de-ai/designengine.ai/files/2885424/parts.pdf)

**Comment by mtholcombe** [comment]
- [X] Added db tables for symbols
- [X] Detached 1st level in nested symbols, then writing master symbols to db
- [X] Prepped frontend for symbol data
- [ ] Write symbols in artboards to db w/ master assoc
- [ ] Frontend symbol render
