### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/designengine.ai#589]
- [x] logging out and back in from any state is taking me to my last uploaded project rendered blank
- [x] Uploaded new avatar and the image collapsed like in the attached. 
- [ ] Need a solution for image sizes that won't fit. Maybe kick back the upload and give minimum specs in the overlay.
- [x] Went to hit Save on my profile and it appears to update the profile but it also brings down the finder window as if it it wants to upload
- [x] When i signed up with a new user then went to the rate this page it automatically recored that I rated the product 5 stars.
- [x] Change Header page title == "Design Engine - Inspect, Extract, & Present Pixel-Perfect Design"
- [ ] ChangeShare title == "Design code, specs, & parts are ready."
- [ ] ChangeShare Description == "Upland-property.sketch"
- [x] Uploaded file and default code had specs already(see attached)
- [x] Determine why the font attached/below didn't appear.

**Comment by jasonfesta** [comment]
Uploaded avatar and it refreshed like this... 

![image](https://user-images.githubusercontent.com/1239243/53489172-5a152380-3a45-11e9-929e-9cf728972da6.png)

**Comment by jasonfesta** [comment]
Uploaded file and default code had specs already?

![image](https://user-images.githubusercontent.com/1239243/53490239-11129e80-3a48-11e9-825e-cf6cc36586e0.png)

**Comment by jasonfesta** [comment]
Determine why this font didn't appear. Should have been installed the other day.

http://dev.designengine.ai/inspect/241/upland-tutorial

![image](https://user-images.githubusercontent.com/1239243/53494055-b1b98c00-3a51-11e9-8ff8-81c10bc21192.png)

**Comment by mtholcombe** [comment]
need this font not bourbon

![image](https://user-images.githubusercontent.com/36906424/53533457-d47a8d80-3aaf-11e9-9479-9f568f0cb42f.png)
