### ISSUE TITLE
make a dedicated url for each projects that is loaded into the iframe & can be distributed via copy and paste for on-device viewing

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/designengine.ai#709]
- [x] Vanilla HTML / CSS
- [x] React based

**Comment by jasonfesta** [comment]
![Editor](https://user-images.githubusercontent.com/1239243/56938080-d44d3d00-6ab4-11e9-87ab-39d64b6074a8.png)

**Comment by mtholcombe** [comment]
HTML / CSS:
http://cdn.designengine.ai/renders/{UPLOAD_ID}/html/${ARTBOARD_TITLE}

React:
http://cdn.designengine.ai/renders/{UPLOAD_ID}/build/
